import {TerrainBaseId, TerrainFeatureId} from '../../models/game-map/terrain';

export const SUITABLE_TERRAIN_FEATURES: Record<TerrainBaseId, TerrainFeatureId[]> = {
  [TerrainBaseId.GRASSLAND]: [TerrainFeatureId.FLOODPLAINS, TerrainFeatureId.MARSH, TerrainFeatureId.WOODS],
  [TerrainBaseId.GRASSLAND_HILLS]: [TerrainFeatureId.WOODS],
  [TerrainBaseId.GRASSLAND_MOUNTAIN]: [],
  [TerrainBaseId.PLAINS]: [TerrainFeatureId.FLOODPLAINS, TerrainFeatureId.RAINFOREST, TerrainFeatureId.WOODS],
  [TerrainBaseId.PLAINS_HILLS]: [TerrainFeatureId.RAINFOREST, TerrainFeatureId.WOODS],
  [TerrainBaseId.PLAINS_MOUNTAIN]: [],
  [TerrainBaseId.DESERT]: [TerrainFeatureId.FLOODPLAINS, TerrainFeatureId.OASIS],
  [TerrainBaseId.DESERT_HILLS]: [],
  [TerrainBaseId.DESERT_MOUNTAIN]: [],
  [TerrainBaseId.TUNDRA]: [TerrainFeatureId.WOODS],
  [TerrainBaseId.TUNDRA_HILLS]: [TerrainFeatureId.WOODS],
  [TerrainBaseId.TUNDRA_MOUNTAIN]: [],
  [TerrainBaseId.SNOW]: [],
  [TerrainBaseId.SNOW_HILLS]: [],
  [TerrainBaseId.SNOW_MOUNTAIN]: [],
  [TerrainBaseId.LAKE]: [],
  [TerrainBaseId.COAST]: [],
  [TerrainBaseId.OCEAN]: [TerrainFeatureId.ICE]
}

// export const SUITABLE_TERRAIN_RESOURCES = {
//   [TerrainResourceId.BANANAS]: [],
//   [TerrainResourceId.CATTLE]: [],
//   [TerrainResourceId.COPPER]: [],
//   [TerrainResourceId.CRABS]: [],
//   [TerrainResourceId.DEER]: [],
//   [TerrainResourceId.FISH]: [],
//   [TerrainResourceId.RICE]: [],
//   [TerrainResourceId.SHEEP]: [],
//   [TerrainResourceId.STONE]: [],
//   [TerrainResourceId.WHEAT]: [],
//   [TerrainResourceId.ALUMINUM]: [],
//   [TerrainResourceId.COAL]: [],
//   [TerrainResourceId.HORSES]: [],
//   [TerrainResourceId.IRON]: [],
//   [TerrainResourceId.NITER]: [],
//   [TerrainResourceId.OIL]: [],
//   [TerrainResourceId.URANIUM]: [],
//   [TerrainResourceId.CITRUS]: [],
//   [TerrainResourceId.COCOA]: [],
//   [TerrainResourceId.COFFEE]: [],
//   [TerrainResourceId.COTTON]: [],
//   [TerrainResourceId.DIAMONDS]: [],
//   [TerrainResourceId.DYES]: [],
//   [TerrainResourceId.FURS]: [],
//   [TerrainResourceId.GYPSUM]: [],
//   [TerrainResourceId.INCENSE]: [],
//   [TerrainResourceId.IVORY]: [],
//   [TerrainResourceId.JADE]: [],
//   [TerrainResourceId.MARBLE]: [],
//   [TerrainResourceId.MERCURY]: [],
//   [TerrainResourceId.PEARLS]: [],
//   [TerrainResourceId.SALT]: [],
//   [TerrainResourceId.SILK]: [],
//   [TerrainResourceId.SILVER]: [],
//   [TerrainResourceId.SPICES]: [],
//   [TerrainResourceId.SUGAR]: [],
//   [TerrainResourceId.TEA]: [],
//   [TerrainResourceId.TOBACCO]: [],
//   [TerrainResourceId.TRUFFLES]: [],
//   [TerrainResourceId.WHALES]: [],
//   [TerrainResourceId.WINE]: []
// }
