import {TerrainResourceId} from '../../models/game-map/terrain';

export const TERRAIN_RESOURCE_ID_TO_CSS_CLASS_MAP = {
  [TerrainResourceId.NONE]: 'm-resource-none',
  [TerrainResourceId.BANANAS]: 'm-resource-bananas',
  [TerrainResourceId.CATTLE]: 'm-resource-cattle',
  [TerrainResourceId.COPPER]: 'm-resource-copper',
  [TerrainResourceId.CRABS]: 'm-resource-crabs',
  [TerrainResourceId.DEER]: 'm-resource-deer',
  [TerrainResourceId.FISH]: 'm-resource-fish',
  [TerrainResourceId.RICE]: 'm-resource-rice',
  [TerrainResourceId.SHEEP]: 'm-resource-sheep',
  [TerrainResourceId.STONE]: 'm-resource-stone',
  [TerrainResourceId.WHEAT]: 'm-resource-wheat',
  [TerrainResourceId.ALUMINUM]: 'm-resource-aluminum',
  [TerrainResourceId.COAL]: 'm-resource-coal',
  [TerrainResourceId.HORSES]: 'm-resource-horses',
  [TerrainResourceId.IRON]: 'm-resource-iron',
  [TerrainResourceId.NITER]: 'm-resource-niter',
  [TerrainResourceId.OIL]: 'm-resource-oil',
  [TerrainResourceId.URANIUM]: 'm-resource-uranium',
  [TerrainResourceId.CITRUS]: 'm-resource-citrus',
  [TerrainResourceId.COCOA]: 'm-resource-cocoa',
  [TerrainResourceId.COFFEE]: 'm-resource-coffee',
  [TerrainResourceId.COTTON]: 'm-resource-cotton',
  [TerrainResourceId.DIAMONDS]: 'm-resource-diamonds',
  [TerrainResourceId.DYES]: 'm-resource-dyes',
  [TerrainResourceId.FURS]: 'm-resource-furs',
  [TerrainResourceId.GYPSUM]: 'm-resource-gypsum',
  [TerrainResourceId.INCENSE]: 'm-resource-incense',
  [TerrainResourceId.IVORY]: 'm-resource-ivory',
  [TerrainResourceId.JADE]: 'm-resource-jade',
  [TerrainResourceId.MARBLE]: 'm-resource-marble',
  [TerrainResourceId.MERCURY]: 'm-resource-mercury',
  [TerrainResourceId.PEARLS]: 'm-resource-pearls',
  [TerrainResourceId.SALT]: 'm-resource-salt',
  [TerrainResourceId.SILK]: 'm-resource-silk',
  [TerrainResourceId.SILVER]: 'm-resource-silver',
  [TerrainResourceId.SPICES]: 'm-resource-spices',
  [TerrainResourceId.SUGAR]: 'm-resource-sugar',
  [TerrainResourceId.TEA]: 'm-resource-tea',
  [TerrainResourceId.TOBACCO]: 'm-resource-tobacco',
  [TerrainResourceId.TRUFFLES]: 'm-resource-truffles',
  [TerrainResourceId.WHALES]: 'm-resource-whales',
  [TerrainResourceId.WINE]: 'm-resource-wine',
}
